apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-sandbox-staging

resources:
  - ../../base

# NOTE: Image tag is promoted from dev via CI/CD workflow
images:
  - name: api-sandbox
    newName: 862087104112.dkr.ecr.us-west-2.amazonaws.com/api-sandbox-dev
    newTag: 21a0d1c

replicas:
  - name: api-sandbox
    count: 1

commonLabels:
  app.kubernetes.io/env: staging

patches:
  - target:
      kind: Ingress
      name: api-sandbox
    patch: |-
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1group.name
        value: api-sandbox-staging
