apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: api-sandbox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: API Sandbox Project
  sourceRepos:
    - 'https://github.com/MacCondon/api-sandbox.git'
  destinations:
    - namespace: api-sandbox-dev
      server: https://kubernetes.default.svc
    - namespace: api-sandbox-staging
      server: https://kubernetes.default.svc
    - namespace: api-sandbox-prod
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
